### ISSUE TITLE
[P3] Two stopped events for step and breakpoint.

### ISSUE THREAD

**Issue by andxu** [vscjavaci/eclipse.jdt.ls#60]
when I steps into a line which contains an existing breakpoint, two stop events will be sent targeting at the same thread id which causes two stack frame requests with same thread id, which will cause vscode report duplicate stack id error:

 
![image](https://user-images.githubusercontent.com/17075863/29853971-b8fb0c62-8d75-11e7-9062-1a0da046bc7e.png)

 

The full log  is here:

[REQUEST]
{"command":"next","arguments":{"threadId":1},"type":"request","seq":26}

[[RESPONSE]]
Content-Length: 87

{"success":true,"request_seq":26,"command":"next","body":{},"seq":35,"type":"response"}

JDI Event: StepEvent@Hello:96 in thread main

send event:org.eclipse.jdt.ls.debug.adapter.Events$StoppedEvent@33256584

[[RESPONSE]]
Content-Length: 124

{"event":"stopped","body":{"threadId":1,"reason":"step","allThreadsStopped":false,"type":"stopped"},"seq":36,"type":"event"}

JDI Event: BreakpointEvent@Hello:96 in thread main

send event:org.eclipse.jdt.ls.debug.adapter.Events$StoppedEvent@6f078744

[[RESPONSE]]
Content-Length: 130

{"event":"stopped","body":{"threadId":1,"reason":"breakpoint","allThreadsStopped":false,"type":"stopped"},"seq":37,"type":"event"}

[REQUEST]
{"command":"threads","type":"request","seq":27}

[[RESPONSE]]
Content-Length: 303

{"success":true,"request_seq":27,"command":"threads","body":{"threads":[{"id":2,"name":"Thread [Attach Listener]"},{"id":3,"name":"Thread [Signal Dispatcher]"},{"id":4,"name":"Thread [Finalizer]"},{"id":5,"name":"Thread [Reference Handler]"},{"id":1,"name":"Thread [main]"}]},"seq":38,"type":"response"}

[REQUEST]
{"command":"threads","type":"request","seq":28}

[[RESPONSE]]
Content-Length: 303

{"success":true,"request_seq":28,"command":"threads","body":{"threads":[{"id":2,"name":"Thread [Attach Listener]"},{"id":3,"name":"Thread [Signal Dispatcher]"},{"id":4,"name":"Thread [Finalizer]"},{"id":5,"name":"Thread [Reference Handler]"},{"id":1,"name":"Thread [main]"}]},"seq":39,"type":"response"}

[REQUEST]
{"command":"stackTrace","arguments":{"threadId":1,"startFrame":0,"levels":20},"type":"request","seq":29}
-->stack frame @393232 #thread1
-->stack frame @393233 #thread1

[[RESPONSE]]
Content-Length: 425

{"success":true,"request_seq":29,"command":"stackTrace","body":{"stackFrames":[{"id":24,"source":{"name":"Hello.java","path":"c:\\java-debug\\java-sample\\src\\Hello.java","sourceReference":0},"line":96,"column":0,"name":"test"},{"id":25,"source":{"name":"Hello.java","path":"c:\\java-debug\\java-sample\\src\\Hello.java","sourceReference":0},"line":100,"column":0,"name":"main"}],"totalFrames":2},"seq":40,"type":"response"}

[REQUEST]
{"command":"stackTrace","arguments":{"threadId":1,"startFrame":0,"levels":20},"type":"request","seq":30}
-->stack frame @393232 #thread1
-->stack frame @393233 #thread1

[[RESPONSE]]
Content-Length: 425

{"success":true,"request_seq":30,"command":"stackTrace","body":{"stackFrames":[{"id":24,"source":{"name":"Hello.java","path":"c:\\java-debug\\java-sample\\src\\Hello.java","sourceReference":0},"line":96,"column":0,"name":"test"},{"id":25,"source":{"name":"Hello.java","path":"c:\\java-debug\\java-sample\\src\\Hello.java","sourceReference":0},"line":100,"column":0,"name":"main"}],"totalFrames":2},"seq":41,"type":"response"}

**Comment by akaroml** [comment]
Duplicate with https://mseng.visualstudio.com/VSJava/VSCode%20for%20Java/_workitems?id=1065728&_a=edit&triage=true
