### ISSUE TITLE
[P0]Should support class/package name with special characters.

### ISSUE THREAD

**Issue by andxu** [vscjavaci/eclipse.jdt.ls#68]
package ab$c;
public class Hello$orld {

}

**Comment by akaroml** [comment]
@andxu please open this issue in https://github.com/eclipse/eclipse.jdt.ls

**Comment by andxu** [comment]
closed as new bugs are created at 
https://github.com/Microsoft/vscode-java-debug/issues/19
https://github.com/redhat-developer/vscode-java/issues/299
